### ISSUE TITLE
old script remake

### ISSUE THREAD

**Issue by ghost** [Mody404/Ddos-Script-Fivem#1]
elsif($variavel == 24) { $payload = "std"; $porta = "3306"; }
elsif($variavel == 25) { $payload = "ripe"; $porta = "30110"; }

hahahahahahahahaahha look this guy (yep look at me )

pasting .pl created in 2k16 (True)

brainless (insulting is wrong )

**Comment by Mody404** [comment]
with the port modification worked for fivem a few months ago

**Comment by Mody404** [comment]
and for the next one a nicer title would be cool.
